### PR TITLE
PHPDocs updates, API Bump, restyling of entire code

### PR DESCRIPTION
**Pull request by JackMD**
This PR includes PHPDoc updates along with API bump and a better restyling of code.

### CODE REVIEW

**Comment by JackMD** [comment]
Also i have tested it and there are no errors.

**Comment by Falkirks** [comment]
Most of this looks good. I will look further when I am at a computer. 

One issue I noticed right off the bat is changing the version? Why is this needed? It breaks my semantic versioning. So I would like if you revert that before I merge.

**Comment by JackMD** [comment]
Okay. I was making it so that it showed which Minecraft PE/BE version it supported. Anyways I have fixed it.

**Comment by JackMD** [comment]
Also most of the issues opened are totally irrelevant. I have tested the plugin and haven't experienced any sort of error.

**Comment by Falkirks** [comment]
Yeah, PocketMine issues are weird like that. A lot of it, is figuring out what part of the setup has gone wrong and adding a safety check to give people a more descriptive error.

**Comment by JackMD** [comment]
@Falkirks I totally agree with you.

**Comment by Falkirks** [comment]
I am happy to merge this now, but I don't use style you use for braces, so I might go through again and change them to be on the same line. But regardless, the PHPDoc stuff is great and it makes the code easier to read.

**Pull request merged**
